version: '3'

services:
  neo4j:
    image: bitnami/neo4j:latest
    container_name: graphrek
    volumes:
      - ./.data:/bitnami
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_PASSWORD=test

  redis:
    image: redis:5-alpine
    container_name: graphrekis
    volumes:
      - ./.redis:/bitnami/redis/data
    ports:
      - 6379:6379
