version: '3'

services:
  neo4j:
    image: neo4j:3.5
    container_name: graphrek
    volumes:
      - ./.data:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/test

  redis:
    image: redis:5-alpine
    container_name: graphrekis
    env_file:
      - .services.env
    volumes:
      - ./.redis:/bitnami/redis/data
    ports:
      - 6379:6379
